guestbook_homepage:
    pattern:  /{page}
    defaults: { _controller: GuestbookBundle:Entry:index, page: 1 }
    requirements:
        page:  \d+

guestbook_routing:
    resource: "@GuestbookBundle/Resources/config/routing/entry.yml"
    prefix:   /book