parameters:
#    guestbook.example.class: Serge\GuestbookBundle\Example
    guestbook.number.page: 3

services:
#    guestbook.example:
#        class: %guestbook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
